- .idea/codeStyles/codeStyleConfig.xml
- .idea/misc.xml
- src/ase/cw/IO/FileReader.java
- src/ase/cw/control/OrderController.java
- src/ase/cw/exceptions/InvalidCustomerIdException.java
- src/ase/cw/exceptions/NoOrderException.java
- test/TestFileReader.java
Added method logic for the controller class
- Data parsing cannot be tested currently.
- Build is not possible, will be fixed as per #24
- Method signatures had to be altered to have `Item` as argument for add & remove items from pending order
- Changed SDK to latest stable Java 11, if that's a problem we can revert.
> Controller logic

- src/ase/cw/control/OrderController.java
- src/ase/cw/gui/OrderFrame.java
Some quick fixes and addition of setters in OrderFrame to be used by OrderController following feedback from @jathanasiou 
I think now OrderController can pass the required data over without further data/object manipulation by OrderFrame
I am leaving this one for you to review/approve in your own time
thanks!
> added OrderFrame setters; related to issue #42

- .idea/misc.xml
- src/ase/cw/control/OrderController.java
- src/ase/cw/gui/OrderFrame.java
`OrderFrame` should now have its items/totals be set by the `OrderController` properly. Please take a look @trz-maier and let me know if that's what you had in mind.
> Improved Gui/controller interactions as per #15

- src/ase/cw/control/OrderController.java
- src/ase/cw/exceptions/EmptyOrderException.java
Also added missing `EmptyOrderException` constructor.
> added order exceptions as per #57

- res/Items.csv
Fixed Issue #65 (Added more items)
> Added more items in items.csv

- res/Orders.csv
- src/ase/cw/control/OrderController.java
- src/ase/cw/gui/OrderFrame.java
- src/ase/cw/model/Order.java
To solve #64 
- Added customer ID validator and exceptions in `OrderController`
- Integrated validator to model and GUI
- Adjusted orders input file to match expected format
> Improved handling of invalid customer IDs as per #64

- src/ase/cw/control/OrderController.java
Just a formatting fix for the generated report.
> added report line break for #63

- src/ase/cw/gui/OrderFrame.java
fixed close window button actions
> fixed #83 and #70

- src/ase/cw/control/OrderController.java
- test/TestOrderController.java
- added testing suite for OrderController
- made OrderController constructor public to allow test instances
It seems that code coverage cannot easily go above 50% unless we restructure a few things in the controller. Namely, lacking tests in OrderItem removal and report generation.
>  Controller testing #81

- src/ase/cw/gui/OrderFrame.java
some minor style changes;
refined search items method;
added comments;
> Refined search items; added comments; 

- src/ase/cw/model/Bill.java
- src/ase/cw/model/OrderItem.java
- Improved discount calculation logic (issue #61).
This also includes implementing comparable interface for the OrderItem class so that OrderItems can be sorted for this discount calculation.
> Improved discount calculation logic (issue #61).

- src/ase/cw/control/OrderController.java
- using platform-dependant line ending
- outputting decimals with only 2 decimal digits
> Fixed Report issues #87

- res/Items.csv
- src/ase/cw/control/OrderController.java
- src/ase/cw/model/Bill.java
Added more discounts (issue #61).
Also made minor change to formatting of report.
> Added more discounts (issue #61).

- src/ase/cw/control/OrderController.java
Writes log to a `log.txt` file on application exit.
> Logger instead of System.out. Issue #119

- src/ase/cw/control/OrderController.java
- src/ase/cw/model/OrderProducerListener.java
- src/ase/cw/model/OrderQueue.java
- src/ase/cw/model/Server.java
- src/ase/cw/utlities/ServerStatusEnum.java
- test/TestServer.java
> Server Fixed

- src/ase/cw/control/OrderController.java
- src/ase/cw/gui/QueueFrame.java
- src/ase/cw/gui/ServerFrame.java
- src/ase/cw/model/Order.java
can now add a random order using GUI buttons; few minor changes;
> random orders can now be added to the queue #111

- src/ase/cw/control/OrderController.java
- src/ase/cw/gui/QueueFrame.java
- src/ase/cw/gui/ServerFrame.java
- src/ase/cw/model/Server.java
- src/ase/cw/view/ServerFrameView.java
known issue:
when closing servers the program waits until the order is processed which is good however the frame appears frozen during that time.
> can now add and remove servers #130 #131

- src/ase/cw/control/OrderController.java
- src/ase/cw/model/OrderQueue.java
- Corrected usage of randomization seed
- Fixed vector queue Vector iteration to avoid Concurrency issues.
>  Random order addition fix for #155 

- src/ase/cw/control/OrderController.java
- src/ase/cw/model/Order.java
- src/ase/cw/model/OrderQueue.java
I added order id for orders in gui if anyone is skeptical. I think this works now but I welcome any comments if this creates any problems or if anyone has a better solution
> fixed #160 (issue with queue order)

- .idea/misc.xml
- src/ase/cw/control/OrderController.java
- src/ase/cw/control/ServerController.java
- src/ase/cw/view/QueueFrame.java
- src/ase/cw/view/ServerFrame.java
- src/ase/cw/view/ServerFrameView.java
- set correctly buttons enable/disable actions
- fixed slider and added log messages
> #150 button enable/disable actions; fixed slider;
